"""Export shared declarative analysis rules; never used by the native runtime."""
from pathlib import Path
import argparse
import json
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'src'))
from dsh_session_insights import analyzer, semantic


def encode(value):
    if isinstance(value, re.Pattern):
        return {'source': value.pattern.replace('(?i)', ''), 'flags': ('i' if value.flags & re.I else '') + ('s' if value.flags & re.S else '')}
    if isinstance(value, dict):
        return {key: encode(item) for key, item in value.items()}
    if isinstance(value, (tuple, list, set)):
        return [encode(item) for item in (sorted(value) if isinstance(value, set) else value)]
    return value

names = ['DSH_KNOWN_RECORD_TYPES', 'WORK_AREA_RULES', 'COMMON_FILE_EXTENSIONS', 'TEXT_ERROR_RULES', 'FAILURE_CAUSE_RULES', 'TOKEN_KEYS', 'ROLE_NAMES']
names += ['SENSITIVE_BLOCK_RE', 'FENCED_CODE_RE', 'EMAIL_RE', 'UUID_RE', 'HOME_UNIX_RE', 'HOME_WINDOWS_RE', 'ABS_UNIX_PATH_RE', 'ABS_WINDOWS_PATH_RE', 'BEARER_RE', 'NAMED_SECRET_RE', 'KNOWN_SECRET_RE', 'LONG_TOKEN_RE', 'CORRECTION_RE', 'USER_ACCEPTANCE_RE', 'CONTENT_DUMP_COMMAND_RE', 'DIAGNOSTIC_COMMAND_RE', 'VERIFICATION_COMMAND_RE', 'STATE_CHANGE_COMMAND_RE', 'FILE_EXTENSION_RE', 'SKILL_MENTION_RE', 'DSH_SANDBOX_DENIED_RE', 'DSH_USER_REJECTED_RE', 'RUNTIME_EXIT_LINE_RE', 'RUNTIME_SUCCESS_LINE_RE', 'RUNTIME_FAILURE_LINE_RE', 'WALL_TIME_LINE_RE', 'TOOL_EVIDENCE_LINE_RE']
data = {name: encode(getattr(analyzer, name)) for name in names}
data.update({name: encode(getattr(semantic, name)) for name in ['FACET_ENUMS', 'AGGREGATE_SECTIONS']})
text = '// Generated by scripts/build_native_rules.py; edit the shared Python declarations.\nexport default ' + json.dumps(data, ensure_ascii=False, indent=2) + '\n'
target = Path(__file__).resolve().parents[1] / 'plugin/lib/rules.js'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
if parser.parse_args().check:
    if target.read_text(encoding='utf-8') != text:
        raise SystemExit('native rules are stale')
else:
    target.write_text(text, encoding='utf-8')
