// Run the installed tarball's Node implementation, with constructed semantic
// outputs. Never calls a model; retained reports are labelled synthetic.
import {resolve,join} from 'node:path'
import {pathToFileURL} from 'node:url'
import {readFile,mkdir,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const [packagePath,outputPath,tarball]=process.argv.slice(2).map(p=>resolve(p))
const importFile=path=>import(pathToFileURL(join(packagePath,path)).href)
const {buildReport}=await importFile('plugin/lib/analyzer.js')
const semantic=await importFile('plugin/lib/semantic.js')
const {Store}=await importFile('plugin/lib/storage.js')
const source=new URL('../tests/fixtures/synthetic-session.jsonl',import.meta.url)
const before=await readFile(source), rows=before.toString().trim().split('\n').map(JSON.parse)
const snapshots=[1,2,3].map(i=>({session:{...rows[0],id:`synthetic-candidate-${i}`},events:rows.slice(1),inheritedEventCount:0}))
await mkdir(outputPath,{recursive:true})
process.env.DSH_HOME=join(outputPath,'profile')
await mkdir(process.env.DSH_HOME,{recursive:true})
const store=new Store(), results=[]
for(const locale of ['en','zh-CN']) {
 const zh=locale==='zh-CN',run=store.create()
 const built=buildReport(snapshots,{now:rows[0].createdAt+86400000,days:30,privacy:'redacted',analysis_depth:'evidence',locale})
 const prepared=semantic.prepareSemantic(store,run,built)
 if(!prepared.batches.length)throw new Error('candidate must exercise a nonempty semantic batch')
 for(const id of prepared.batches){const batch=semantic.getBatch(store,run,id);semantic.submitBatch(store,run,id,{facets:batch.tasks.map(task=>({task_family_id:task.task_family_id,goal:zh?'合成候选验证':'Synthetic candidate verification',task_type:'implementation',interaction_style:zh?'迭代':'Iterative',instruction_handling:'followed',tool_execution:'strong',verification_quality:'strong',handoff_quality:'clear',frictions:[],strengths:[zh?'包含验证证据':'Validation evidence present'],outcome_inference:'mostly_achieved',evidence_refs:[task.evidence[0].id]}))})}
 const input=semantic.prepareAggregate(store,run), e=input.evidence[0]
 const item={title:zh?'合成测试观察':'Synthetic test observation',text:zh?'此报告验证候选渲染，语义输出由测试构造，并非真实模型生成。':'This report tests candidate rendering. Semantic outputs are constructed, not generated by a real model.',supporting_task_family_ids:[e.task_family_id],evidence_refs:[e.id],confidence:'medium',measurement:'inferred'}
 const aggregate=Object.fromEntries(input.output_contract.required_sections.map(section=>[section,[section==='recommendations'?{...item,recommendation_key:'validation',singleton_observation:true,action:zh?'检查结果':'Inspect results',copy_prompt:zh?'验证结果。':'Validate the result.'}:item]]))
 semantic.submitAggregate(store,run,aggregate)
 const final=semantic.finalize(store,run)
 const report=JSON.parse(await readFile(final.data,'utf8'))
 if(report.semantic_analysis.status!=='complete' || report.totals.sessions!==3)throw new Error('incomplete candidate report')
 results.push({locale,...final,batches:prepared.batches.length,sessions:report.totals.sessions})
}
const digest=b=>createHash('sha256').update(b).digest('hex')
if(digest(await readFile(source))!==digest(before))throw new Error('source fixture changed')
const receipt={status:'pass',scope:'isolated installed npm package; synthetic semantic outputs; no model',packagePath,tarball,tarballSha256:digest(await readFile(tarball)),sourceSha256:digest(before),sourceUnchanged:true,reports:results}
await writeFile(join(outputPath,'candidate-validation.json'),JSON.stringify(receipt,null,2)+'\n')
console.log(JSON.stringify(receipt,null,2))
